<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9lQ459n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9lQ459n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9lQ459n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9lQ459n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9lQ459n\App_KernelDevDebugContainer([
    'container.build_hash' => '9lQ459n',
    'container.build_id' => 'a48d1a78',
    'container.build_time' => 1692284954,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9lQ459n');
