<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFekPY9e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFekPY9e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFekPY9e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFekPY9e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFekPY9e\App_KernelDevDebugContainer([
    'container.build_hash' => 'FekPY9e',
    'container.build_id' => 'f0591ea3',
    'container.build_time' => 1692100908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFekPY9e');
